### ISSUE TITLE
Regex based string comparison

### ISSUE THREAD

**Issue by ameily** [trailofbits/differ#1]
Add regex support in the `StringComparator` class to verify that the string matches a pattern. Something like:

```yaml
templates:
  - comparators:
    - id: stdout
      pattern: '^hello [wW]orld$'
```

The stdout and stderr comparators inherit from the string comparator class, so verify the pattern works for both stdout and stderr content.
