### ISSUE TITLE
String variables

### ISSUE THREAD

**Issue by ameily** [trailofbits/differ#2]
Similar to the `IntVariable`, create a new `StringVariable` that generates values based on:

- a list of specific values
- a regex pattern

For example, the following variable config should produce the string `hello world!` and then generate 3 strings that match the regex pattern provided:

```yaml
templates:
  - variables:
     name:
       type: str
       values:
         - 'hello world!'

       regex:
         pattern: 'hello [a-zA-Z0-9]{1,10}'
         size: 3
```

Like the `IntVariable` the `values` and `regex` configs can be used separately or together.

Use a library such as [exrex](https://github.com/asciimoo/exrex) to generate strings based on a regex pattern.
