### ISSUE TITLE
Add Production CI Checks

### ISSUE THREAD

**Issue by ameily** [trailofbits/differ#23]
When we are ready to open source and release DIFFER, we'll want to add several CI checks for production code, including:

**`pip-audit`**

```yaml
# update .github/workflows/ci.yml
pip-audit:
  runs-on: ubuntu-22.04
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: 'Generate requirements.txt'
      run: |
        pipx run pipfile-requirements Pipfile.lock > requirements.txt

    - uses: pypa/gh-action-pip-audit@v1.0.0
      with:
        inputs: requirements.txt
```

**`dependabot`**

```yaml
version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
```
