### ISSUE TITLE
Comparators for Hooks

### ISSUE THREAD

**Issue by ameily** [trailofbits/differ#26]
To support network-based binaries, both client and server, we'll need the ability to compare the results of the peer binary to verify that the binary being evaluated works correctly. For example, evaluating an HTTP server, we would run curl against the original and debloated server version. Then, we would take the output of curl (stdout/stderr, downloaded file, exit code, etc.) and compare the call targeting the original server versus the debloated server. We would deem that the debloated version is not working properly if the client reports any differences.

This issue will add a new configuration setting to trace templates that controls if and how to compare the results of any generic hooks that were run. For example:

```yaml
original: some_http_client

templates:
  - arguments: 'GET http://localhost:8080/thing'
    hooks:
      setup:
        ./server --port 8080
    
      comparators:
        - stdout
        - stderr
        - exit_code
    
    comparators:
      - stdout
      - stderr
      - exit_code
```

Here, the `hooks` block has its own list of comparators to run against all output.
