### ISSUE TITLE
Variable References

### ISSUE THREAD

**Issue by ameily** [trailofbits/differ#31]
DIFFER needs to support dereferencing a variable's value within a comparator. For example, testing a sample such as `mkdir`, we'll be generating filenames to make sure the debloated copy correctly detects invalid filenames. Then, we'll need to make sure that the directory was actually created. Without variable references, we would need many different templates to acomplish this. With a variable reference, we can create a single template:

```yaml
name: coreutils_mkdir

templates:
  - arguments: "{{dirname}}"
    variables:
      dirname:
        type: str
        regex:
          pattern: '[A-Z][a-z0-9]{3,9}'
          count: 5

    comparators:
      - id: file
        filename:
          variable: dirname
        exists: true
        type: directory
```

Now, a single template can evaluate multiple traces based on the generated value.

Variable references would be opt-in for each comparator configuration.
