### ISSUE TITLE
Template Input Files

### ISSUE THREAD

**Issue by ameily** [trailofbits/differ#4]
Templates need the ability to specify input files that are used during execution. Input files must be run through the jinja2 engine to populate any variables and then the generated file must be copied to the destination. Input files must support the following:

- A source file name that is relative to the project.yml file location, similar to how relative paths for binaries are resolved
- Run the input file through jinja2 for each trace context
- An optional destination
  - If not specified, copy the input file to the trace directory and preserve the filename
  - Destinations can be absolute or relative to the trace directory

For example:

```ini
; config.ini
verbosity={{verbosity}}
```

```yaml
templates:
  - input_files:
      - source: config.ini
    
    variables:
      verbosity:
        type: int
        values:
          - 0
          - 1
          - 2
```
