### ISSUE TITLE
Jinja2 environment variables

### ISSUE THREAD

**Issue by ameily** [trailofbits/differ#51]
Jinja2 templates may need access to current environment variables. For example, the `chown` sample needs to know the current user name. A simple solution in this case would be to expose `os.environ` as a global template variable available to all Jinja2 templates. That way, the `chown` can run:

```yaml
- arguments: '{{env.USER}}:sudo file1'
  comparators:
    - stdout
    - stderr
    - exit_code
```
