### ISSUE TITLE
Template stdin file and content

### ISSUE THREAD

**Issue by ameily** [trailofbits/differ#6]
Trace templates will need the ability to pipe in stdin content either from a file on disk or a string from the configuration. There are several use cases that stdin must support:

1. Pipe a string that was defined in the configuration file to the process
2. Pipe a file on disk to the process
3. Pipe an input file that was generated to the process

For example,

```yaml
templates:
  - stdin:
       value: "Hello world!"  # use case 1: pipe string

  - stdin:
       file: /path/to/data.bin  # use case 2: pipe from a file on disk

  - stdin:
       file: messages.txt  # use case 3: pipe from an input file that is generated

    input_files:
      - source: messages.txt
```
